# Created with WinGet Updater using komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

InstallerType: zip
Installers:
  - Architecture: neutral
    InstallerSha256: 28500CC2DB0A1C6DA1B628A7F063282A72CF45DAE76B744C73FCB8EBCDC8F128
    InstallerUrl: https://github.com/oleg-shilo/cs-script/releases/download/v4.10.0.0/cs-script.win.v4.10.0.0.zip
ManifestType: installer
ManifestVersion: 1.9.0
NestedInstallerFiles:
  - PortableCommandAlias: css
    RelativeFilePath: css.exe
NestedInstallerType: portable
PackageIdentifier: oleg-shilo.cs-script
PackageVersion: 4.10.0.0
ReleaseDate: 2025-07-29
