# Created with WinGet Updater using komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

License: MIT
LicenseUrl: https://github.com/oleg-shilo/cs-script/blob/HEAD/LICENSE
ManifestType: defaultLocale
ManifestVersion: 1.9.0
PackageIdentifier: oleg-shilo.cs-script
PackageLocale: en-US
PackageName: cs-script
PackageUrl: https://github.com/oleg-shilo/cs-script
PackageVersion: 4.10.0.0
Publisher: oleg-shilo
PublisherSupportUrl: https://github.com/oleg-shilo/cs-script/issues
PublisherUrl: https://github.com/oleg-shilo
ReleaseNotes: "- `-ng:csc` is now using running csc.exe with the \"magic\" `/shared` parameter that keeps `VBCSCompiler.exe` running and improves the compilation performance dramatically.\r\n  - `-ng:csc` is now routed to `-ng:csc-inproc`\r\n  - WDBG:\r\n  - Added disposing abandoned user sessions\r\n  - fixed problem with local methods in the call stack"
ReleaseNotesUrl: https://github.com/oleg-shilo/cs-script/releases/tag/v4.10.0.0
ShortDescription: C# Script execution engine
